services:
  server:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    attach: true
    tty: true

    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/target
        - action: sync+restart
          path: .env
          target: /app/.env
        - action: sync+restart
          path: .env.development
          target: /app/.env.development
        - action: sync+restart
          path: .env.production
          target: /app/.env.production

  db:
    attach: true
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      PGUSER: $PG__USER
      POSTGRES_USER: $PG__USER
      POSTGRES_PASSWORD: $PG__PASSWORD
    ports:
      - ${PG__PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
